In [8]:
import pandas as pd
from fuzzywuzzy import fuzz, process
sentiment_df = pd.read_csv("annotation.csv")

comment_id_df =pd.read_csv("EDA.csv")
# Iterate through each sentiment comment and find the closest matching comment ID

comment_id_df

,Comment Text,Comment Score,Parent Comment ID,Comment Depth,Sentiment,Date
0,For anyone trying to report this on Facebook: ...,484,t3_94rfy3,0,-1,2018-08-05 13:00:41
1,"I would also suggest those that live overseas,...",207,t3_94rfy3,0,0,2018-08-05 13:29:52
2,There's an app called FireChat that will allow...,808,t3_94rfy3,0,0,2018-08-05 13:12:09
3,Please use this thread if you know of any way ...,131,t3_94rfy3,0,0,2018-08-05 12:46:23
4,Gilded to help boost OP's post.\n\nI highly re...,400,t3_94rfy3,0,1,2018-08-05 12:55:27
...,...,...,...,...,...,...
5785,"XD as a non-Dhakaiyan I can assure you, I don'...",2,t1_gp9o7xt,2,0,2021-03-01 05:37:13
5786,I used to hear handling mara in school but now...,2,t1_gpab7w7,2,0,2021-03-01 14:38:47
5787,Yes bro.,2,t1_gpa5rvu,2,0,2021-03-01 10:08:27
5788,LOL I was kidding man. I wanted my post to loo...,1,t1_gpdnv2f,3,0,2021-03-02 09:01:44
5789,I feel dumb,2,t1_gpebnr1,4,-1,2021-03-02 10:13:52

In [9]:
sentiment_df

,Comments,20110011,20110200,23120007,Sentiment_Human
0,Elon Musk set us all up to see him as a heroic...,-1,-1,-1,-1
1,AL politician admits to beating children on Na...,-1,-1,-1,-1
2,NID chara Hobe na vaccine nawa jabe na? :/ Tha...,0,-1,0,0
3,I know right? HOW COULD THEY,0,0,-1,0
4,Among us homies india is the most hated one.,-1,-1,-1,-1
...,...,...,...,...,...
97,ðŸ’¯ agreed,0,0,1,0
98,Oh- even better!!!! Than countries like Indone...,1,1,1,1
99,Great work! Hope your cousin keeps it up.,0,1,1,1
100,much needed in this time... \n\nPray for Bangl...,1,1,1,1
101,He was right indeed.,0,0,1,0

In [10]:
comment_id_mapping = {}
for sentiment_comment in sentiment_df["Comments"]:
    closest_match = process.extractOne(sentiment_comment, comment_id_df["Comment Text"])
    comment_id_mapping[sentiment_comment] = closest_match[2]

# Add the matched Comment IDs to the sentiment data frame
sentiment_df["Comment ID"] = sentiment_df["Comments"].map(comment_id_mapping)

In [11]:
sentiment_df

,Comments,20110011,20110200,23120007,Sentiment_Human,Comment ID
0,Elon Musk set us all up to see him as a heroic...,-1,-1,-1,-1,356
1,AL politician admits to beating children on Na...,-1,-1,-1,-1,561
2,NID chara Hobe na vaccine nawa jabe na? :/ Tha...,0,-1,0,0,3938
3,I know right? HOW COULD THEY,0,0,-1,0,3693
4,Among us homies india is the most hated one.,-1,-1,-1,-1,1090
...,...,...,...,...,...,...
97,ðŸ’¯ agreed,0,0,1,0,4457
98,Oh- even better!!!! Than countries like Indone...,1,1,1,1,3724
99,Great work! Hope your cousin keeps it up.,0,1,1,1,4342
100,much needed in this time... \n\nPray for Bangl...,1,1,1,1,3578
101,He was right indeed.,0,0,1,0,4455

In [13]:
 csv_filename = "human_eval"
sentiment_df.to_csv(csv_filename, index=False)